#[cfg(test)]
mod tests {
    use recursa::Parse;

    use super::*;
    use crate::ast::test_support::*;

    #[test]
    fn parse_create_sequence_plain() {
        let lexed = crate::lex("CREATE SEQUENCE s1");
        assert_eq!(lexed.errors().count(), 0, "lex errors in input");
        let mut input = lexed.input();
        let stmt_parsed = CreateSequenceStmt::parse(&mut input).unwrap();
        let stmt = stmt_parsed.ast();
        assert!(stmt.persistence.is_none());
        assert!(stmt.options.is_empty());
        assert!(input.is_eof());
    }

    #[test]
    fn parse_create_sequence_options() {
        let lexed = crate::lex(
            "CREATE SEQUENCE s1 AS integer INCREMENT BY 2 MINVALUE 1 MAXVALUE 100 START WITH 5 CACHE 10 CYCLE",
        );
        assert_eq!(lexed.errors().count(), 0, "lex errors in input");
        let mut input = lexed.input();
        let stmt_parsed = CreateSequenceStmt::parse(&mut input).unwrap();
        let stmt = stmt_parsed.ast();
        assert_eq!(stmt.options.len(), 7);
        assert!(input.is_eof());
    }

    #[test]
    fn parse_create_sequence_no_minvalue_owned_by() {
        let lexed = crate::lex(
            "CREATE SEQUENCE s1 NO MINVALUE NO MAXVALUE NO CYCLE OWNED BY t.col",
        );
        assert_eq!(lexed.errors().count(), 0, "lex errors in input");
        let mut input = lexed.input();
        let stmt_parsed = CreateSequenceStmt::parse(&mut input).unwrap();
        let stmt = stmt_parsed.ast();
        assert_eq!(stmt.options.len(), 4);
        assert!(input.is_eof());
    }

    #[test]
    fn parse_create_sequence_temp_if_not_exists() {
        let lexed = crate::lex("CREATE TEMPORARY SEQUENCE IF NOT EXISTS s1");
        assert_eq!(lexed.errors().count(), 0, "lex errors in input");
        let mut input = lexed.input();
        let stmt_parsed = CreateSequenceStmt::parse(&mut input).unwrap();
        let stmt = stmt_parsed.ast();
        assert!(matches!(
            stmt.persistence,
            Some(CreatePersistence::Temporary)
        ));
        assert!(stmt.if_not_exists.is_some());
        assert!(input.is_eof());
    }

    #[test]
    fn parse_create_sequence_owned_by_none() {
        let lexed = crate::lex("CREATE SEQUENCE s1 OWNED BY NONE");
        assert_eq!(lexed.errors().count(), 0, "lex errors in input");
        let mut input = lexed.input();
        let stmt_parsed = CreateSequenceStmt::parse(&mut input).unwrap();
        let stmt = stmt_parsed.ast();
        assert_eq!(stmt.options.len(), 1);
        assert!(matches!(stmt.options[0], SeqOption::OwnedBy(_)));
        assert!(input.is_eof());
    }

    // Added in 15: research, PostgreSQL 17, "Changes to existing statements"
    // (commit f7567f9e53d, back-patched to 15 and 16). REL_15_19 gram.y
    // `SeqOptElem: ... | LOGGED` (4741) and `| UNLOGGED` (4781). The same
    // `SeqOptElem` is the item of `OptSeqOptList` (CREATE SEQUENCE),
    // `SeqOptList` (ALTER SEQUENCE), `OptParenthesizedSeqOptList` (the
    // `GENERATED ... AS IDENTITY (...)` list) and
    // `alter_identity_column_option: SET SeqOptElem`.
    #[cfg(feature = "since-pg15")]
    #[test]
    fn sequence_logged_options_are_modelled() {
        check_statement_forms(
            &[
                "CREATE SEQUENCE s LOGGED",
                "CREATE SEQUENCE s UNLOGGED",
                "CREATE SEQUENCE s START 1 UNLOGGED",
                "CREATE SEQUENCE IF NOT EXISTS s LOGGED",
                "ALTER SEQUENCE s LOGGED",
                "ALTER SEQUENCE s UNLOGGED",
                "ALTER SEQUENCE IF EXISTS s LOGGED START 2",
                "CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY (LOGGED))",
                "CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY (UNLOGGED))",
                "CREATE TABLE t (a int GENERATED BY DEFAULT AS IDENTITY (START WITH 4 UNLOGGED))",
                "ALTER TABLE t ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY (UNLOGGED)",
                "ALTER TABLE t ALTER COLUMN a SET LOGGED",
                "ALTER TABLE t ALTER COLUMN a SET UNLOGGED",
                "ALTER TABLE t ALTER COLUMN a SET GENERATED ALWAYS SET UNLOGGED",
            ],
            &[
                "CREATE SEQUENCE s NO LOGGED",
                "CREATE SEQUENCE s NOT LOGGED",
                "ALTER SEQUENCE s LOGGED 1",
                "CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY (NO UNLOGGED))",
                "ALTER TABLE t ALTER COLUMN a SET LOGGED 1",
            ],
        );
    }

    // Added in 15, so rejected in 14: REL_14_24 gram.y `SeqOptElem` (4391)
    // has neither `LOGGED` nor `UNLOGGED`. 14 still takes `UNLOGGED` before
    // the `SEQUENCE` keyword (`OptTemp`) and `SET LOGGED`/`SET UNLOGGED` as
    // an `alter_table_cmd`.
    #[cfg(not(feature = "since-pg15"))]
    #[test]
    fn sequence_logged_options_are_rejected_before_15() {
        assert_statements_rejected(&[
            "CREATE SEQUENCE s LOGGED",
            "CREATE SEQUENCE s UNLOGGED",
            "CREATE SEQUENCE s START 1 UNLOGGED",
            "ALTER SEQUENCE s LOGGED",
            "ALTER SEQUENCE s UNLOGGED",
            "CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY (LOGGED))",
            "CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY (UNLOGGED))",
            "ALTER TABLE t ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY (UNLOGGED)",
            "ALTER TABLE t ALTER COLUMN a SET LOGGED",
            "ALTER TABLE t ALTER COLUMN a SET UNLOGGED",
        ]);
        assert_statements_parse(&[
            "CREATE UNLOGGED SEQUENCE s",
            "ALTER SEQUENCE s SET LOGGED",
            "ALTER SEQUENCE s SET UNLOGGED",
            "ALTER TABLE t SET UNLOGGED",
            "CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY (START WITH 4))",
        ]);
    }
}
